name: Download
on:
  workflow_dispatch:

jobs:
  download:
    runs-on: macos-12
    steps:
      - name: List installers
        run: softwareupdate --list-full-installers

      - name: Download installer
        run: |
          softwareupdate --download --fetch-full-installer --full-installer-version 11.7.6

      - name: Create disk
        run: |
          hdiutil create -o /tmp/MacBigSur -size 13000m -volname MacBigSur -layout SPUD -fs HFS+J
          hdiutil attach /tmp/MacBigSur.dmg -noverify -mountpoint /Volumes/MacBigSur

      - name: createinstallmedia
        run: sudo /Applications/Install\ macOS\ Big\ Sur.app/Contents/Resources/createinstallmedia --volume /Volumes/MacBigSur --nointeraction

      - name: Detach disk
        run: hdiutil detach -force "/Volumes/Install macOS Big Sur"

      - name: Convert to ISO
        run: |
           hdiutil convert /tmp/MacBigSur.dmg -format UDTO -o ~/Desktop/MacBigSur.cdr
           mv ~/Desktop/MacBigSur.cdr MacBigSur.iso
           rm -Rf /tmp/MacBigSur.dmg

      - name: Push to GHCR
        run: |
          brew install oras || true
          oras login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} || true
          oras push ghcr.io/${{github.repository}}:latest --artifact-type application/vnd.acme.rocket.config ./MacBigSur.iso
